---
title: "Cumulative Analyses"
author: "Joshua Bell"
date: "11/22/2021"
output: html_document
---

```{r setup, include=FALSE}
pkgs <- c("dplyr", "tidyr", "readr", "data.table", "magrittr", "here", "plotly", "ggplot2", "gghalves", "ggthemes", "patchwork", "tidybayes", "correlation", "knitr", "datawizard", "brms")
for(i in pkgs){
  if(!i %in% rownames(installed.packages())){ 
    install.packages(i) 
    library(i, character.only = TRUE)
  }
  else(library(i, character.only = TRUE))
}
# Sets stan backend to cmdstan. You will need to install the cmdstanr package and set up the toolchain.
options("mc.cores" = parallel::detectCores(), "brms.backend" = "cmdstan", tinytex.verbose = T)

b = 2400/parallel::detectCores()
i = 24000/parallel::detectCores()
ch = parallel::detectCores()
co = parallel::detectCores()

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = TRUE, fig.width = 12, fig.height = 8)

ppt_m_fulltrials <- read_csv(here::here("data", "study_two", "ppt_m_fulltrials.csv")) %>%
  filter(ppid != "d1-003") %>%
  mutate(phase = factor(phase, levels = c("start", "begin", "out", "lift", "replace", "return", "returned"))) %>%
  as.data.table()

steamvr_m_fulltrials <- read_csv(here::here("data", "study_two", "steamvr_m_fulltrials.csv")) %>%
  as.data.table()

ppt_m <- read_csv(here::here("data", "study_one", "ppt_manual.csv")) %>%
        mutate(
          order = fcase(
            block_num < 3, "pre",
            block_num == 4, "first",
            block_num == 5, "second"
          )
        ) %>%
        bind_rows(
            read_csv(here::here("data", "study_two", "ppt_manual.csv"))) %>% 
        as.data.table() %>%
        mutate(time = factor(x = time,
            levels = c("pre", "post"),
            labels = c("Pre", "Post")),
        order = factor(x = order,
            levels = c("pre", "first", "second"),
            labels = c("Pre", "First", "Second")),
        tracking = "PPT",
        block_num = fifelse(time == "Pre", 1, 4))


steamvr_m <- fread(here::here("data", "study_one", "steamvr_manual.csv")) %>%
        bind_rows(
            fread(here::here("data", "study_two", "steamvr_manual.csv"))) %>% 
        as.data.table() %>%
        mutate(time = factor(x = time,
            levels = c("pre", "post"),
            labels = c("Pre", "Post")),
        tracking = "SteamVR")

tracker_comparison_m <- bind_rows(ppt_m, steamvr_m) %>%
        mutate(tracking = factor(tracking, levels = c("PPT", "SteamVR"))) %>%
        as.data.table()

landmark <- read_csv(here::here("data", "study_one", "landmark.csv")) %>%
    bind_rows(
        read_csv(here::here("data", "study_two", "landmark.csv")),
        read_csv(here::here("data", "study_three", "landmark.csv"))) %>%
    dplyr::filter(
      !ppid %in% c(
          "d1-004", "d1-006"
        )) %>%
    mutate(error_std = standardize(lapse_fix_error),
         target = factor(lapse_fix_target,
            levels = c("Elbow", "Forearm", "Wrist")),
         error_cm = lapse_fix_error * 100,
         forearmlength = forearmlength * 100,
         forearmlength_std = standardize(forearmlength),
         time = factor(time,
            levels = c("pre", "post"),
            labels= c("Pre", "Post")),
         order = factor(x = order, 
          levels = c("pre", "first", "second"),
            labels = c("Pre", "First", "Second"))) %>%
            as.data.table()

participant_info <- fread(here::here("data", "1_tooluseinvr", "participant_info.csv")) %>%
    select(
        ppid, age, gender, fatigue, performance_hypothesis
    ) %>%
    bind_rows(
        fread(here::here("data", "2_toolusenotinvr", "participant_info.csv")) %>%
            select(
                ppid, age, gender, fatigue, performance_hypothesis
            ),
        fread(here::here("data", "3_avatartooluse", "participant_info_coded.csv")) %>%
            mutate(fatigue = fatigue_yn) %>%
            select(
                ppid, age, gender, fatigue, performance_hypothesis
            )
    ) %>%
    mutate(
        study = fcase(
            ppid %like% "d1-0", "VR Tool-use (No Avatar)",
            ppid %like% "d2-0", "Real Tool-use",
            ppid %like% "d3-0", "VR Tool-use (Avatar)",
            default = NA
        ),
        fatigue = factor(fatigue, levels = c(0, 1), labels = c("No", "Yes")),
        performance_hypothesis = factor(performance_hypothesis, levels = c(0, 1), labels = c("No", "Yes"))
    )

ppt_tool <- read_csv(here::here("data", "study_one", "ppt_tool.csv")) %>%
    bind_rows(read_csv(here::here("data", "study_two", "ppt_tool.csv")) %>%
  dplyr::filter(tracked == "shaft")) %>%
  as.data.table()

ppt_combined <- ppt_m %>% bind_rows(ppt_tool) %>% as.data.table()

ppt_combined[
  ,
  time := fcase(time == "Pre", "pre",
                time == "Post", "post",
                is.na(time), "tool-use")]

ppt_forearmlength <- landmark[,.(forearmlength = mean(forearmlength)),
                                by = c("ppid")] %>% merge(ppt_m, by = "ppid") %>%
                                as.data.table()
```

```{r landmark-fatigue}
participant_info_and_landmark <- landmark %>%
    left_join(participant_info, by = "ppid") %>%
    mutate(
        overall_trial = fifelse(
            time == "Post",
            trial + 18,
            trial
        ),
        study = fcase(
            ppid %like% "d1-0", "VR Tool-use (No Avatar)",
            ppid %like% "d2-0", "Real Tool-use",
            ppid %like% "d3-0", "VR Tool-use (Avatar)",
            default = NA
        )
    )

(lm_empirical <- participant_info_and_landmark %>%
    ggplot(aes(
        y = error_cm,
        x = overall_trial,
        fill = fatigue,
        color = fatigue,
        group = interaction(time, fatigue)
    )) +
    geom_point(alpha = .2) +
    geom_line(
        data = participant_info_and_landmark %>%
            group_by(fatigue, time, overall_trial, target) %>%
            summarise(
                error_cm = mean(error_cm, na.rm = TRUE)
            ),
        aes(y = error_cm)
    ) +
    geom_hline(yintercept = 0, linetype = "dashed") +
    facet_grid(~target) +
    theme_tidybayes() +
    scale_x_discrete(expand = c(0, 0)) +
    scale_y_continuous(limits = c(-25, 25), expand = c(0, 0)) +
    scale_fill_manual(
        breaks = c("No", "Yes"),
        values = c("#001015", "#09A1D7"),
        labels = c("No", "Yes")
    ) +
    scale_color_manual(
        breaks = c("No", "Yes"),
        values = c("#001015", "#09A1D7"),
        labels = c("No", "Yes")
    ) +
    labs(y = "Error (cm)", x = "Trial", fill = "Fatigue", color = "Fatigue", title = "Body Landmark Task Response Distributions") +
    theme(
        axis.text.y = element_text(hjust = 0),
        title = element_text(size = 16),
        text = element_text(size = 14, color = "black"),
        strip.background = element_blank(),
        strip.placement = "inside",
        strip.switch.pad.wrap = unit(0, "in"),
        panel.background = element_rect(fill = "transparent", colour = NA),
        legend.background = element_rect(fill = "transparent", colour = NA),
        plot.background = element_rect(fill = "transparent", colour = NA)
    ))

participant_info_and_landmark %>%
    group_by(fatigue, time, study, target) %>%
    dplyr::filter(
      target != "Elbow"
      ) %>%
    summarise(
        mean_error = mean(error_cm, na.rm = TRUE),
        sd_error = sd(error_cm, na.rm = TRUE)
    ) %>% as.data.table() %>%
    dcast(
        formula = fatigue + study ~ time + target,
        value.var = "mean_error",
        fun.aggregate = mean
    ) %>%
    mutate(
        "Forearm Change" = Post_Forearm - Pre_Forearm,
        "Wrist Change" = Post_Wrist - Pre_Wrist
    )
```